name: CI

on:
  pull_request:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: ./

      - name: Test
        run: cd test && sbt++field scala2 test
